---
title: "Covid-19 Case Data"
author: "Bob Rudis edited by John Minter"
date: 'Started 2020-04-11, Last modified: 2020-04-11'
output:
  html_document:
    css: ../theme/jm-gray-vignette.css
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment=NA)
```

```{r doFirst, message=FALSE}
library(cdccovidview)
# current version
packageVersion("cdccovidview")
library(cdccovidview)
library(hrbrthemes)
library(tidyverse)

hosp <- laboratory_confirmed_hospitalizations()

summary(hosp)
```

```{r makeAgeF}
age_f <- c(
  "0-4 yr", "5-17 yr", "18-49 yr", "50-64 yr", "65+ yr", "65-74 yr", "75-84 yr", "85+"
)
```

Plot the results

```{r plotResults, fig.width=9}
plt <- mutate(hosp, start = mmwr_week_to_date(mmwr_year, mmwr_week)) %>% 
  filter(!is.na(weekly_rate)) %>% 
  filter(catchment == "Entire Network") %>% 
  select(start, network, age_category, weekly_rate) %>%  
  filter(age_category != "Overall") %>% 
  mutate(age_category = factor(age_category, levels = age_f)) %>% 
  ggplot() +
  geom_line(aes(start, weekly_rate)) +
  scale_x_date(date_breaks = "2 weeks", date_labels = "%b\n%d") +
  facet_grid(network~age_category) +
  labs( x = NULL,
        y = "Rates per 100,000 pop",
        title = "COVID-NET Weekly Rates by Network and Age Group",
        caption = sprintf("Source: COVID-NET Accessed on %s",Sys.Date())) +
  theme(axis.text=element_text(size=10),
        axis.title=element_text(size=14),
        plot.title = element_text(hjust = 0.5)) + # center the title
  NULL

print(plt)
```


```{r savePng, warning=FALSE, message=FALSE}
strOutPng <- "plt/Confirmed-Hospitalizations.png"

# we want the png to be close to 1024x768...
ggsave(plt, file=strOutPng, width=9.0, height=6.0,
       units="in", dpi=113.7778)

strOutJpg <- "plt/Confirmed-Hospitalizations.jpg"

# we want the png to be close to 1024x768...
ggsave(plt, file=strOutJpg, width=9.0, height=6.0,
       units="in", dpi=113.7778)
```
